### ISSUE TITLE
Send image to group chat

### ISSUE THREAD

**Issue by soend** [topkecleon/otouto#82]
Is there a way to upload images instead of using the web page preview? If not maybe this could be a new feature..
https://core.telegram.org/bots/api#sendphoto

**Comment by topkecleon** [comment]
Please read the README before submitting questions.
All Telegram bot API methods are supported, including sending images with sendPhoto.
For an example, see rmspic.lua or dilbert.lua.

For some plugins, like xkcd.lua or apod.lua, web page previews are used because the messages use markdown or html formatting which is not supported yet in image captions.
