### ISSUE TITLE
Improve administration plugin

### ISSUE THREAD

**Issue by unomas** [topkecleon/otouto#89]
- In command 'gadd' add line for save the 'group id' in the table.

- With this you can add a command to send a message to all groups. I have written the command and it works correctly, I leave it below:

```lua
{ -- /globalmsg
  triggers = utilities.triggers(self_.info.username, self_.config.cmd_pat):t('globalmsg', true).table,

  command = 'globalmsg \\[texto]',
  privilege = 5,
  interior = false,

  action = function(self, msg)
    local text = utilities.input(msg.text) 
    if text ~= '' then	
      for _, group in pairs(self.database.administration.groups) do
        if (not group.flags[1]) then -- no unlisted groups
          utilities.send_message(group.id, text, true, nil, true)
        end
      end
    end
  end
},
```

- I have tried using cli to delete messages through the plugin administration, but I have not achieved anything. Any ideas? I want to create a mute command to silence users, keeping them in the group but not being able to speak.

**Comment by topkecleon** [comment]
You can already do this, since the groups are indexed by their IDs.
Your for loop would be

``` lua
for id, group in pairs(self.database.administration.groups) do
  if not group.flags[1] then
    utilities.send_message(id, text, true, nil, true)
  end
end
```

Regarding the mute feature, the message IDs used by the bot API are not the same as the message IDs used by tg-cli (which are simply numbered in the order received by the client). Unfortunately it's not currently possible to delete a message without some amount of scripting on the tg-cli client.

**Comment by wrxck** [comment]
@unomas If you're looking to implement message deletion using tg-cli to "mute" users, you can delete the message using the tg-cli variant of the message ID, since it wouldn't matter which order it's in if you've used something like:

```Lua
if msg.from.id == x then -- where x is the muted user
    -- proceed to delete message
end
```

If I recall correctly, tg-cli's delete message function is something like:

```Lua
delete_msg (msg.id, ok_cb, false)
```

Also, @topkecleon I believe he was suggesting re-introducing the /broadcast command

**Comment by topkecleon** [comment]
But the message ID you send to tg-cli will not be that message's ID in the tg session. That's why it wouldn't work; correct me if I'm wrong because I'd love to be wrong about this.

Regarding /broadcast: That's a pretty disgusting way to do things tbh. Just use a channel. Odds are someone will want the imaginary karma and forward it to all your groups anyway.

**Comment by unomas** [comment]
Any idea for count members in a group? 
With this: bindings.getChatMembersCount(chat_id) doesn't work.

I'm still working to delete messages hahaha

**Comment by topkecleon** [comment]
All bindings functions expect a table for an argument. Call it like this:

`bindings.getChatMembersCount{chat_id=-987654321}`

**Comment by unomas** [comment]
It works now. In case anyone needs it:
```lua
members_count = bindings.getChatMembersCount{chat_id = -987654321}
num_members = members_count.result -- Get the number of members
```
